language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
before_script:
    - git clone https://github.com/IATI/IATI-Websites.git
    - cd IATI-Extra-Documentation/en
    - ln -s ../../IATI-Websites/iatistandard/_templates/ ./
    - ln -s ../../IATI-Websites/iatistandard/_static/ ./
    - cd ../..
    - mkdir docs
    - cd docs
    - git init
    - cd ..
script:
    - ./combined_gen.sh
deploy:
    local-dir: docs-copy/en/_build/dirhtml/
    provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_TOKEN
    on:
        all_branches: true
